version: '3'

services:

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Minsk
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
