# Generated by Django 5.1.7 on 2025-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('books', models.ManyToManyField(related_name='libraries', to='books.book')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
    ]
