# Generated by Django 5.1.7 on 2025-04-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_site', models.URLField(max_length=250)),
                ('biography', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.authorbio'),
        ),
    ]
