# Generated by Django 5.1.7 on 2025-05-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_genre_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': [('can_get_statistic', 'Can get genres statistic')]},
        ),
    ]
